Version update mp5
OpenLiberty/draft-guide-cloud-ibm pull request #122
Opened 2022-02-24 17:50 UTC by gkwan-ibm

address issue: https://github.com/OpenLiberty/guides-common/issues/759

2022-05-18 18:09 UTC, dmuelle requested changes
ID edit suggestion for the README- lmk if you have any questions. Thanks

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +There are different cloud-based solutions for running your Kubernetes workloads. A cloud-based infrastructure enables you to focus on developing your microservices without worrying about low-level in
```suggestion
Different cloud-based solutions are available to run your Kubernetes workloads. A cloud-based infrastructure enables you to focus on developing your microservices without worrying about low-level infrastructure details for deployment. Using a cloud helps you to easily scale and manage your microservices in a high-availability setup.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +IBM Cloud Kubernetes Service (IKS) is part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster where you can deploy your microservices. You will use it with IBM Cloud Container R
```suggestion
The IBM Cloud Kubernetes Service (IKS) is part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster where you can deploy your microservices. In this guide, you will use it with the IBM Cloud Container Registry, which is a private registry that is used to store and distribute your container images.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +IBM Cloud Kubernetes Service (IKS) is part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster where you can deploy your microservices. You will use it with IBM Cloud Container R
I haven't corrected it throughout this guide, but IBM terminology says not to use "IKS" as an abbreviation for "IBM Kubernetes Service"

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +The two microservices you will deploy are called `system` and `inventory`. The system microservice returns the JVM system properties of the running container. It also returns the pod’s name in the HT
```suggestion
The two microservices you will deploy are called `system` and `inventory`. The `system` microservice returns the JVM system properties of the running container. It also returns the pod’s name in the HTTP header, making replicas easy to distinguish from each other. The `inventory` microservice adds the properties from the `system` microservice to the inventory. This configuration demonstrates how to establish communication between pods inside a cluster.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +You will use Helm to deploy these microservices to IBM Cloud using Open Liberty Helm charts. Helm is a package manager for {kube}. It uses templates to generate {kube} yaml files and then deploys and
```suggestion
You will use Helm to deploy these microservices to IBM Cloud by using Open Liberty Helm charts. Helm is a package manager for {kube}. It uses templates to generate {kube} YAML files and then deploys and manages them as releases in your cluster. 
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +The service used to expose your deployments has a type of `NodePort`. This means you can access these services from outside of your cluster via a specific port. In this case, `nodePort` is not specif
```suggestion
The service used to expose your deployments has a type of `NodePort` service that enables you to access these services from outside of your cluster through a specific port. In this case, `nodePort` is not specified and the ports are randomized so you must obtain the ports before you make requests to the services. You must also obtain the public IP address of your cluster. Other ways to expose your services are available, such as by using a `LoadBalancer` service type or  an `Ingress` resource. In production, you typically use an `Ingress` resource.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +Take note of the `Public IP` in the command's output. This will be the hostname you substitute into commands later in this guide.
```suggestion
Take note of the `Public IP` in the command's output. You will substitute this value as the hostname into commands later in this guide.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +The first URL returns system properties and the name of the pod in an HTTP header called `X-Pod-Name`. To view the header, you can use the `-I` option in the `curl` when making a request to `{system-
```suggestion
The first URL returns system properties and the name of the pod in an HTTP header called `X-Pod-Name`. To view the header, you can use the `-I` option in the `curl` when making a request to  the `{system-api}` URL. The second URL adds properties from `system-service` to the inventory.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +A few tests are included for you to test the basic functionality of the microservices. If a test failure occurs, then you might have introduced a bug into the code. To run the tests, wait for all pod
```suggestion
A few tests are included for you to test the basic functionality of the microservices. If a test fails, then you might have introduced a bug into the code. To run the tests, wait until all pods are in the ready state before proceeding further. The default properties that are defined in the `pom.xml` file are:
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
>  == Deploying new version of system microservice
```suggestion
== Deploying a new version of system microservice
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +Optionally, you might want to make changes to your microservice and learn how to redeploy the updated version of your microservice. In this section, you will bump the version of the `system` microser
```suggestion
Optionally, you might want to make changes to your microservice and redeploy the updated version. In this section, you will bump the version of the `system` microservice to `2.0-SNAPSHOT` and redeploy the new version of the microservice. You can redeploy a microservice by using Helm to upgrade the release.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +Observe that in this case the `system` microservice is running in the pod called `system-app-ibm-open-libe-85c85949c-lb49d`. Substitute the name of your pod into the following command to see more det
```suggestion
In this case, the `system` microservice is running in the pod called `system-app-ibm-open-libe-85c85949c-lb49d`. Substitute the name of your pod into the following command to see more details about the pod.
```

2022-05-18 18:09 UTC, dmuelle commented on README.adoc
> +You have just deployed two microservices to IBM Cloud. You have learned to use Helm to install your microservices on a {kube} cluster using the Open Liberty helm chart.
```suggestion
You just deployed two microservices to IBM Cloud. You learned to use Helm to install your microservices on a {kube} cluster by using the Open Liberty helm chart.
```

2022-05-19 14:32 UTC, gkwan-ibm commented on README.adoc
> +IBM Cloud Kubernetes Service (IKS) is part of IBM’s public cloud offerings. It provides a hosted Kubernetes cluster where you can deploy your microservices. You will use it with IBM Cloud Container R
Removed the IKS

2022-05-19 14:36 UTC, dmuelle approved these changes
LGTM

2022-05-20 14:19 UTC, uhryniuk approved these changes
Windows test passed

2022-05-20 14:25 UTC, merged