Minor updates
OpenLiberty/draft-guide-cloud-ibm pull request #139
Opened 2022-10-28 19:56 UTC by jgawor

Additional updates.

2022-10-31 21:03 UTC, gkwan-ibm commented
In the "Deploying a new version of system microservice" section, the instructions before `docker tag...`, `docker push...`, and `kubectl set image...` commands require adding the following statement:
- Remember to replace `us.icr.io to` your registry and `[your-namespace]` with the namespace you created earlier in the guide.

2022-10-31 21:05 UTC, gkwan-ibm requested changes
In the "Deploying a new version of system microservice" section, the instructions before `docker tag...`, `docker push...`, and `kubectl set image...` commands require adding the following statement:
- Remember to replace `us.icr.io to` your registry and `[your-namespace]` with the namespace you created earlier in the guide.

2022-11-02 03:11 UTC, jgawor commented
@jakub-pomykala thanks for making that change while i was away!

2022-11-02 16:14 UTC, gkwan-ibm approved these changes

2022-11-02 16:15 UTC, merged